apiVersion: v1
kind: Service
metadata:
  name: claims-agentic-service
  namespace: claims-app
  labels:
    app: claims-agentic-app
spec:
  type: LoadBalancer
  selector:
    app: claims-agentic-app
  ports:
    - name: http
      port: 80
      targetPort: 8501
